# Generated by Django 4.1.2 on 2022-10-12 06:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimages',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 12, 11, 47, 23, 99136)),
        ),
    ]
