# Generated by Django 4.1.2 on 2022-10-12 07:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0002_alter_userimages_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimages',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 12, 13, 6, 18, 144960)),
        ),
    ]
